language: node_js

node_js:
  - 10
  - 12
  - 14

os:
  - linux
  - osx
  - windows

cache: npm

install:
  - npm install

git:
  quiet: true
  depth: 1

script:
  - npm run build

before_script:
  - npm install mocha rollup @babel/register @babel/core rimraf nyc -g

after_success:
  - npm run test:coveralls
